// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFzac5uIVNJEBkwXfUdDORNIz4IToAaOo',
    appId: '1:1064624920362:web:945ffb7f2031478a473053',
    messagingSenderId: '1064624920362',
    projectId: 'dars66firestore',
    authDomain: 'dars66firestore.firebaseapp.com',
    storageBucket: 'dars66firestore.appspot.com',
    measurementId: 'G-JTJ2Z6ZRHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDR0Uur0WhNZhbP8aagd9kGDaYqVLwVjk',
    appId: '1:1064624920362:android:bc16e704b42f7494473053',
    messagingSenderId: '1064624920362',
    projectId: 'dars66firestore',
    storageBucket: 'dars66firestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeWenAOfvQ3Kd3c3eeD2Ou4mZgxoSWKwo',
    appId: '1:1064624920362:ios:5ba9cf89099892ed473053',
    messagingSenderId: '1064624920362',
    projectId: 'dars66firestore',
    storageBucket: 'dars66firestore.appspot.com',
    iosBundleId: 'com.example.verySimpleOnlineShopCubit',
  );

}